#569 fixed issue with correct error message not showing on full-doc when uri is not present
Requested Url: http://www.europeana.eu/portal/full-doc.html?  on host www.europeana.eu.

==========
org.springframework.web.bind.MissingServletRequestParameterException: Required java.lang.String parameter 'uri' is not present at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter$ServletHandlerMethodInvoker.

git-svn-id: https://www.europeanalabs.eu/svn/europeana/trunk@925 3c7f12e8-d31e-4037-9ce9-7a8ea9e2c7c8